#!/bin/bash

if [ ! "$(docker network ls | grep web)" ]; 
    then
        echo "Creating Web network ..."
        docker network create web
    else
        echo "Web network already exists... Skipping Step"
fi

docker image system -f --filter "until=24h"

docker-compose -f ./env/docker-compose.development.yml up --build

read -p "Press any key to continue." x