version: '3.5'
services:
  traefik:
    image: traefik:v2.10.1
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=web
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --api.insecure=true
      - --certificatesresolvers.le.acme.email=${LETSENCRYPT_MAIL}
      - --certificatesresolvers.le.acme.storage=/etc/ssl/certs/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --log.level=DEBUG
      - --log.filePath=/etc/traefik/traefik.log
      - --log.format=json
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.traefik.rule=Host(`${DOMAIN_NAME}`)
      - traefik.http.routers.traefik.tls.certresolver=le
      - traefik.http.routers.traefik.entrypoints=websecure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/ssl/certs:/etc/ssl/certs
      - /etc/traefik:/etc/traefik

  detactive_api:
    build: api
    restart: always
    environment:
      - DETACTIVE_DB_URL=${DETACTIVE_DB_URL}
      - STICKER_DB_URL=${STICKER_DB_URL}
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.api.rule=Host(`${DOMAIN_NAME}`) && PathPrefix(`/api`)
      - traefik.http.services.api.loadbalancer.server.port=3000
      - traefik.http.routers.api.tls.certresolver=le
      - traefik.http.routers.api.entrypoints=websecure
    depends_on:
      - db
    networks:
      - web
      - internal

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./api/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.pgadmin.rule=Host(`${DOMAIN_NAME}`) && PathPrefix(`/pgadmin`)
      - traefik.http.services.pgadmin.loadbalancer.server.port=80
      - traefik.http.routers.pgadmin.tls.certresolver=le
      - traefik.http.routers.pgadmin.entrypoints=websecure
    networks:
      - web
      - internal

networks:
  web:
    external: true
  internal:
    external: false
