version: '3.5'
services:
  traefik:
    image: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/ssl/certs:/etc/ssl/certs
      - /etc/traefik:/etc/traefik
    networks:
      - web

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./api/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal

  api:
    build: api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.port=3000"
      - "traefik.http.routers.api.rule=Host(`test-api.detactive.de`) && PathPrefix(`/api`)"
    depends_on:
      - db
    networks:
      - web
      - internal

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    labels:
      - "traefik.port=80"
      - traefik.http.routers.pgadmin.rule=(Host(`test-api.detactive.de`) && PathPrefix(`/pgadmin`))
    networks:
      - web
      - internal

networks:
  web:
    external: true
  internal:
    external: false
