version: '3.5'
services:
  traefik:
    image: traefik
    restart: always
    env_file:
      - .env
    command:
      - --entrypoints.web.address=:80
      - --providers.docker
      - --api.insecure
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/ssl/certs:/etc/ssl/certs
      - /etc/traefik/traefik.log:/etc/traefik/traefik.log

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./api/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - web

  api:
    build: api
    restart: always
    env_file:
      - .env
    labels:
      - traefik.http.routers.api.rule=Host(`test-api.detactive.de`) && PathPrefix(`/api`)
    depends_on:
      - db
    networks:
      - web

networks:
  web:
    external: true
