version: '3.3'
services:
  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - "6380:6380"
    volumes:
      - cache:/db

  api:
    container_name: api
    build: api
    restart: always
    ports:
      - "8080:8080"

volumes:
  cache:
    driver: local
