version: '3.3'
services:
  gateway:
    container_name: gateway
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./gateway/nginx:/etc/nginx/nginx.conf

  certbot:
    image: certbot/certbot:latest
    depends_on:
      - gateway
    command: >-
      certonly --reinstall --webroot --webroot-path=/var/www/certbot --email detactive.app@gmail.com --agree-tos --no-eff-email -d ${HOSTNAME}

  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./api/db/init.sql:/docker-entrypoint-initdb.d/init.sql/

  api:
    container_name: api
    build: api
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
