version: '3.3'
services:
  acme:
    container_name: acme
    image: neilpang/acme.sh:latest
    env_file:
      - .env
    command:
      - mkdir -p /var/www/${ACME_DOMAIN}
      - acme.sh --issue -d ${ACME_DOMAIN} --webroot /var/www/${ACME_DOMAIN}
      - acme.sh --install-cert \ --domain ${ACME_DOMAIN} \ --cert-file /var/www/${ACME_DOMAIN}/cert.pem \ --key-file /var/www/${ACME_DOMAIN}/key.pem \ --fullchain-file /var/www/${ACME_DOMAIN}/fullchain.pem

  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./api/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    container_name: api
    build: api
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
