version: '3.3'
services:
  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./api/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    container_name: api
    build: api
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
