version: '3.5'
services:
  traefik:
    image: traefik
    restart: always
    network_mode: host
    env_file:
      - .env
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=web
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --api.insecure
      - --certificatesresolvers.le.acme.email=detactive.app@gmail.com
      - --certificatesresolvers.le.acme.storage=/etc/ssl/certs/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.api.service=api@internal
      - traefik.http.routers.my-app.rule=Host(`test-api.detactive.de`)
      - traefik.http.routers.traefik.tls.certresolver=le
      - traefik.http.routers.traefik.entrypoints=websecure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/ssl/certs:/etc/ssl/certs
      - /etc/traefik/traefik.log:/etc/traefik/traefik.log

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./api/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal

  detactive_api:
    build: api
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.detactive_api.rule=Host(`test-api.detactive.de`) && PathPrefix(`/api`)
      - traefik.http.services.detactive_api.loadbalancer.server.port=3000
      - traefik.http.routers.detactive_api.tls.certresolver=le
      - traefik.http.routers.detactive_api.entrypoints=websecure
    depends_on:
      - db
    networks:
      - web
      - internal

networks:
  web:
    external: true
  internal:
    external: false
