version: '3.3'
services:
  user-db:
    restart: always
    container_name: user-db
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - cache:/user-db

  api_server:
    restart: always
    container_name: api_server
    build: api_server
    ports:
      - "8080:8080"

volumes:
  cache:
