version: '3.3'
services:
  user-db:
    container_name: user-db
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/user-db

  blueprint-db:
    container_name: blueprint-db
    image: redis
    restart: always
    ports:
      - "6380:6380"
    volumes:
      - cache:/blueprint-db

  api_server:
    container_name: api_server
    build: api_server
    restart: always
    ports:
      - "8080:8080"

volumes:
  cache:
    driver: local
