version: '3.9'
services:
  user-db:
    container_name: user-db
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - cache:/user-db

  server:
    container_name: server
    build: server
    ports:
      - "8080:8080"

volumes:
  cache:
