version: '3.5'
services:
  traefik:
    image: traefik:v2.10.1
    restart: always
    ports:
      - 80:80
      - 443:443
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=web
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --api.insecure=false
      - --certificatesresolvers.le.email=${LETSENCRYPT_MAIL}
      - --certificatesresolvers.le.storage=/etc/ssl/certs/acme.json
      - --certificatesresolvers.le.tlschallenge=true
      - --log.level=DEBUG
      - --log.filePath=/etc/traefik/traefik.log
      - --log.format=json
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/ssl/certs:/etc/ssl/certs
      - /etc/traefik:/etc/traefik
    networks:
      - web

  detactive_api:
    build:
      context: api
    restart: always
    ports:
      - 3000:3000
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.detactive_api.rule=Host(`${DOMAIN_NAME}`)
      - traefik.http.services.detactive_api.loadbalancer.server.port=3000
      - traefik.http.routers.detactive_api.tls.certresolver=le
      - traefik.http.routers.detactive_api.entrypoints=websecure
    networks:
      - web

networks:
  web:
    external: true
