version: '3.3'
services:
  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - shared:/data/:rw
      - ./nginx:/etc/nginx
      - /etc/letsencrypt/live:/etc/letsencrypt/live
    depends_on:
      - certbot

  certbot:
    image: certbot/certbot
    env_file:
      - .env
    volumes:
      - shared:/data/:rw
    command:
      [
        "/bin/sh",
        "-c",
        "certonly --webroot -w /var/www/certbot --email detactive.app@gmail.com --agree-tos --no-eff-email -d test-api.detactive.de"
      ]

  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./api/db/init.sql:/docker-entrypoint-initdb.d/init.sql/

  api:
    container_name: api
    build: api
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"

volumes:
  shared:
