version: '3.9'
services:
  user-db:
    container_name: user-db
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - cache:/user-db

  api_server:
    container_name: api_server
    build: server
    ports:
      - "8080:8080"

volumes:
  cache:
