version: '3.3'
services:
  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - cache:/db
    environment:
      POSTGRES_PASSWORD: b814dc1ee44c62b78d1b48e3ff2a43effee817b234fdc0de75db05a5013aaecf

  api:
    container_name: api
    build: api
    restart: always
    ports:
      - "8080:8080"

volumes:
  cache:
    driver: local
