version: '3.3'
services:
  gateway:

    container_name: gateway
    image: nginx
    restart: always
    ports:
      - "443:443"
      - "80:80"
    env_file:
      - .env
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf/:rw
      - ./gateway/certbot/www:/var/www/certbot/:ro

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw

  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./api/db/init.sql:/docker-entrypoint-initdb.d/init.sql/:rw

  api:
    container_name: api
    build: api
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
