version: '3.3'
services:
  user-db:
    container_name: user-db
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/user-db

  api_server:
    container_name: api_server
    build: api_server
    restart: always
    network_mode: "host"
    ports:
      - "127.0.0.1:8080:8080"

volumes:
  cache:
