log:
  level: INFO
  filePath: "/etc/traefik/traefik.log"
  format: json


api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"
  
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: lets_encrypt

certificatesResolvers:
  lets_encrypt:
    acme:
      tlschallenge: true
      email: "detactive.app@gmail.com"
      storage: "/etc/ssl/certs/acme.json"

providers:
  docker:
    exposedByDefault: false
