providers:
  docker:
    exposedByDefault: false
    network: web

entryPoints:
  http:
    address: ":80"


certificatesResolvers:
  le:
    acme:
      tlschallenge: true
      email: "detactive.app@gmail.com"
      storage: "/etc/ssl/certs/acme.json"