version: '3.5'
services:
  detactive_api:
    build:
      context: ../
    restart: always
    env_file:
      - ../.env
    ports:
      - 3000:3000
    depends_on:
      - postgres

  postgres:
    image: postgres:16.1
    restart: always
    env_file:
      - ../.env
    volumes:
      - ../db/db_data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ../.env
    depends_on:
      - postgres
    ports:
      - 5050:80