version: '3.5'
services:
  detactive_api:
    build:
      context: ../
    restart: always
    env_file:
      - ../.env
    ports:
      - 3000:3000
    networks:
      - web

  postgres:
    image: postgres:16.1
    restart: always
    env_file:
      - ../.env
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ../.env
    environment:
      - SCRIPT_NAME=/pgadmin
    depends_on:
      - postgres
    ports:
      - 5050:5050
    networks:
      - web

networks:
  web:
    external: true
