version: "3.5"
services:
  detactive_api:
    build:
      context: ../api
      dockerfile: ../api/DockerfileFast
    restart: always
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - ../api/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../api/db/data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file: .env
    ports:
      - 5050:80
    depends_on:
      - db
