name: API Server Release Build

on:
  push:
    branches: [ "release-0.0.1" ]
  pull_request:
    branches: [ "release-0.0.1" ]

jobs:
  build:
    runs-on:
      labels: api_server

    steps:
    - uses: actions/checkout@v3

    - name: Load environment variables
      run: |
        set -o allexport
        [ -f .env ] && source .env
        set +o allexport
    
    - name: install/setup dependencies
      run: |
        sudo apt-get update
        sudo apt install docker-compose -y
        sudo docker rm api_server -f

    - name: open ports
      run: |
        sudo ufw allow 22
        sudo ufw allow http
        sudo ufw allow https
        sudo ufw enable
    
    - name: start docker containers
      run: docker-compose -f "docker-compose.yml" up -d --build
      
      
