name: API Server Release Build

on:
  push:
    branches: [ "release-0.0.1" ]
  pull_request:
    branches: [ "release-0.0.1" ]

jobs:
  build:
    runs-on:
      labels: api_server

    steps:
    - uses: actions/checkout@v3
    
    - name: Create external Web network
      run: |
        if [ ! "$(docker network ls | grep web)" ]; then
          echo "Creating Web network ..."
          docker network create web
        else
          echo "Web network already exists... Skipping Step"
        fi

    - name: Install/Setup dependencies
      run: |
        sudo apt-get update
        sudo apt install docker-compose -y
        sudo docker rm traefik -f
        sudo docker rm api_server -f

    - name: Start production services
      run: |
        sudo docker-compose up -d --build
