name: API Server Release Build

on:
  push:
    branches: [ "release-0.0.1" ]
  pull_request:
    branches: [ "release-0.0.1" ]

env:
  DOMAIN: test-api.detactive.de

jobs:
  build:
    runs-on:
      labels: api_server

    steps:
    - uses: actions/checkout@v3
    
    - name: install/setup dependencies
      run: |
        sudo apt-get update
        sudo apt install docker-compose -y
        sudo docker rm api_server -f
        sudo snap install core
        sudo snap refresh core
        sudo snap install --classic certbot

    - name: open ports
      run: |
        sudo ufw allow 22
        sudo ufw allow 8080
        sudo ufw allow 5050
        sudo ufw allow http
        sudo ufw allow https
        sudo ufw enable

    - name: generate certs
      run: |
        sudo ln -s /snap/bin/certbot /usr/bin/certbot
        sudo certbot certonly --standalone -d $DOMAIN --staple-ocsp -m max@maxbeier.dev --agree-tos  
    
    - name: start docker containers
      run: docker-compose -f "docker-compose.yml" up -d --build
      
      
