name: Docker Image CI

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

jobs:
  build:
    runs-on:
      labels: api-server

    steps:
    - uses: actions/checkout@v3
    
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt install docker-compose -y
        
    - name: open ports
      run: |
        sudo ufw allow 8080
        sudo ufw enable
    
    - name: start docker containers
      run: docker-compose -f "docker-compose.yml" up -d --build
      
      
