name: Docker Image CI

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

jobs:
  build:

    runs-on:
      labels: api-server

    steps:
    - uses: actions/checkout@v3
    
    - name: start docker containers
      run: docker-compose -f "docker-compose.yml" up -d --build
      
      
