name: API Server Release Build

on:
  pull_request:
    branches: ["release-0.0.1"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install/Setup dependencies
        run: |
          sudo apt-get update
          sudo apt install docker-compose -y
          if [ ! "$(docker network ls | grep web)" ]; then
            echo "Creating Web network ..."
            docker network create web
          else
            echo "Web network already exists... Skipping Step"
          fi

      - name: Start production services
        run: |
          sudo docker-compose -f ./env/docker-compose.production.yml up --build -d

      - name: Build and push Docker image
        run: |
          docker build -t my-api-image:latest .
          docker tag my-api-image:latest my-api-image:release-0.0.1
          docker push my-api-image:latest
          docker push my-api-image:release-0.0.1

      - name: Delete unused Docker images
        run: |
          docker system prune --force --all

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: path/to/artifact

  cleanup:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Delete artifacts
        run: |
          rm -rf path/to/artifact
        if: always() # Ensure this step runs even if previous steps fail
