name: API Release Build

on:
  push:
    branches: ["production"]
  pull_request:
    branches: ["production"]

jobs:
  install:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install/Setup dependencies
        run: |
          sudo apt-get update
          sudo apt install docker-compose -y
          if [ ! "$(docker network ls | grep web)" ]; then
            echo "Creating Web network ..."
            docker network create web
          else
            echo "Web network already exists... Skipping Step"
          fi

  build:
    runs-on: self-hosted
    needs: install
    steps:
      - name: Start production services
        run: |
          sudo docker-compose --env-file /etc/.env -f ./docker-compose.yml up --build -d

  cleanup:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Delete all docker artifacts
        run: |
          docker system prune --force --all --filter "until=48h"
    if: always()
