name: API Server Release Build

on:
  push:
    branches: ["production"]
  pull_request:
    branches: ["production"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install/Setup dependencies
        run: |
          sudo apt-get update
          sudo apt install docker-compose -y
          if [ ! "$(docker network ls | grep web)" ]; then
            echo "Creating Web network ..."
            docker network create web
          else
            echo "Web network already exists... Skipping Step"
          fi

      - name: Start production services
        run: |
          sudo docker-compose -f ./docker-compose.yml up --build -d

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: /artifacts

  cleanup:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Delete artifacts
        run: |
          rm -rf /artifacts
          docker system prune --force --all
        if: always() # Ensure this step runs even if previous steps fail
