name: API Server Release Build

on:
  push:
    branches: [ "release-0.0.1" ]
  pull_request:
    branches: [ "release-0.0.1" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Install/Setup dependencies
      run: |
        sudo apt-get update
        sudo apt install docker-compose -y
        if [ ! "$(docker network ls | grep web)" ]; then
          echo "Creating Web network ..."
          docker network create web
        else
          echo "Web network already exists... Skipping Step"
        fi

        sudo docker rm -f env_traefik_1
        sudo docker rm -f env_detactive_api_1

    - name: Start production services
      run: |
        sudo docker-compose -f ./env/docker-compose.production.yml up --build -d
      